### ISSUE TITLE
Adding fingerprint coverage for Maria DB Enterprise

### ISSUE THREAD

**Issue by ecastellanos-r7** [rapid7/recog#123]
Nexpose was unable to fingerprint MariaDB - Enterprise as noted in the log trace below. Looking at the banners.xml file, enterprise is not showing in the list. Below is the fingerprint for Maria DB to hopefully be added in the mysql_banners.xml. 

2017-02-15T11:26:26 [INFO] [Thread: xx.x.x:54810/TCP] [Site: Test site] [mysql.banners] Matching against banner: 5.5.5-10.1.21-MariaDB-enterprise 
2017-02-15T11:26:26 [INFO] [Thread: x.x.x.x:54810/TCP] [Site: Test site] [mysql.banners] No matching fingerprint found for banner: 5.5.5-10.1.21-MariaDB-enterpris

https://github.com/rapid7/recog/blob/master/xml/mysql_banners.xml

</fingerprint>
<fingerprint pattern="^(?:\d{1,2}.\d{1,3}.[a-f\d]{1,3}-)?(\d{1,2}.\d{1,3}.[a-f\d]{1,4})-MariaDB-enterprise$" flags="REG_ICASE">
<description>MariaDB MariaDB Enterprise Edition</description>
<example service.version="5.5.34">5.5.34-MariaDB-enterprise</example>
<example service.version="10.1.21">5.5.5-10.1.21-MariaDB-enterprise</example>
<param pos="1" name="service.version"/>
<param pos="0" name="service.vendor" value="MariaDB"/>
<param pos="0" name="service.family" value="MySQL"/>
<param pos="0" name="service.product" value="MariaDB"/>
</fingerprint>

**Comment by pdeardorff-r7** [comment]
Thanks @ecastellanos-r7 this was just merged!  You can verify see it in action via recog by running something like this: 

```
pdeardorff@pdeardorff ~/work/recog
 % echo '5.5.5-10.1.21-MariaDB-enterprise' | bin/recog_match xml/mysql_banners.xml
MATCH: {"matched"=>"MariaDB MariaDB Enterprise Edition", "service.version"=>"10.1.21", "service.vendor"=>"MariaDB", "service.family"=>"MySQL", "service.product"=>"MariaDB", "service.edition"=>"Enterprise Edition", "service.protocol"=>"mysql", "fingerprint_db"=>"mysql.banners", "data"=>"5.5.5-10.1.21-MariaDB-enterprise"}

```
