### ISSUE TITLE
Fingerprint for MariaDB 0ubuntu0 

### ISSUE THREAD

**Issue by ddoanr7** [rapid7/recog#156]
Hi team,

I'm looking to add coverage for MariaDB 0ubuntu0. I working off #155 . From the scan log, we received the following version from the banner request.

Appreciate your guidance. Thank you

> Nomatching fingerprint found for banner:  5.5.5-10.0.31-MariaDB-0ubuntu0.16.04.2

> Installed software (from Administrative credentials): SoftwareFingerprint [[certainty=1.0][description=Ubuntu mariadb-client-10.0 10.0.31-0ubuntu0.16.04.2][family=null][product=mariadb-client-10.0][softwareClass=null][vendor=Ubuntu][version=10.0.31-0ubuntu0.16.04.2]]

> package libmysqlclient20 has source: mysql-5.7
deb:libmysqlclient20 version:5.7.19-0ubuntu0.16.04.1

`<fingerprint pattern="^(\d{1,2}\.\d{1,3}\.\d{1,4})-MariaDB-\dubuntu\d\.(\d{1,2}\.\d\d)[\.\d]*(?:-log)?$">`
`<description>MariaDB MariaDB on Ubuntu 16.04</description>
    <example service.version="5.7.19" os.version="16.04">5.5.5-10.0.31-MariaDB-0ubuntu0.16.04.2</example>
    <param pos="1" name="service.version"/>
    <param pos="0" name="service.vendor" value="Oracle"/>
    <param pos="0" name="service.family" value="MySQL"/>
    <param pos="0" name="service.product" value="MySQL"/>
    <param pos="0" name="os.vendor" value="Ubuntu"/>
    <param pos="0" name="os.family" value="Linux"/>
    <param pos="0" name="os.product" value="Linux"/>
    <param pos="2" name="os.version"/>
	</fingerprint> `

**Comment by tsellers-r7** [comment]
Danh,
  Thanks for opening this issue.  This should be covered as of release 2.1.16.
