### ISSUE TITLE
Fix or remove JRuby test target

### ISSUE THREAD

**Issue by gschneider-r7** [rapid7/recog#238]
JRuby has been failing for a while. We should fix/update the travis-ci config, remove JRuby from testing, and/or allow it to fail without failing the whole build.

It looks like the travis worker is now defaulting to Java 11 and the JRuby version specified is probably not compatible.

**Comment by tsellers-r7** [comment]
Here is the relevant error in the logs

```
unsupported Java version "11", defaulting to 1.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

[32;1m** Updating RubyGems to the latest compatible version for security reasons. **[0m
[32;1m** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **[0m

unsupported Java version "11", defaulting to 1.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[32mjruby-9.1.9.0 - #importing gemset /home/travis/.rvm/gemsets/jruby/global.gems[0m|/-\|/-\|.-\|/-\|/-.|/-\.
```

I think the important part is `Illegal reflective access by org.jruby.util.io.FilenoUtil `

Similar problems were reported here and appear to be related to `jruby-launcher`

https://github.com/jruby/jruby-launcher/issues/27
https://github.com/jruby/jruby/issues/5736#issuecomment-530313123

**Comment by tsellers-r7** [comment]
Also, as a note that the error `unsupported Java version "11", defaulting to 1.7` _should_ be fixed in updated versions of jruby.   I say _should_ because I'm seeing mixed comments in various comments in GitHub

https://github.com/jruby/jruby-openssl/issues/157
https://github.com/jruby/jruby-openssl/issues/175

**Comment by tsellers-r7** [comment]
Based on http://rubies.travis-ci.org/ it appears that we'd have to go to `jruby-head` if we want newer `jruby`.
