### ISSUE TITLE
EOL 1.9.3 support

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/recog#26]
2/23/2015, 1.9.3 will be EOL.  Metasploit is also making this change (or maybe they did already -- I don't know for sure).

Recog should drop 1.9.3 support too.

**Comment by gschneider-r7** [comment]
We're planning to go with 2.1 as the minimum supported version for nexpose-client if that helps you decide for Recog. See https://github.com/rapid7/nexpose-client/issues/95 for our discussion.

**Comment by hmoore-r7** [comment]
2.1.x makes sense

**Comment by shuckins-r7** [comment]
@jhart-r7 @hmoore-r7 Metasploit is on 2.1.5 as of yesterday: https://community.rapid7.com/docs/DOC-3006

**Comment by jhart-r7** [comment]
*nod* -- 2.1.x makes sense.  We can probably move next week or wait for the official date.
