### ISSUE TITLE
HMI device no assigned to proper Os.Device

### ISSUE THREAD

**Issue by nstylepro** [rapid7/recog#285]
https://github.com/rapid7/recog/blob/c2beb75492c2938a4006bb8781214181c4edb457/xml/snmp_sysdescr.xml#L6315

This is an HMI (there is one more in the repo) that is 'HMI controller' yet it is under Os.Device='Monitoring'
Is this intentional or bug? if it's intentional please describe why

**Comment by hdm** [comment]
This looks like a bug and the correct value should be `HMI Controller` to match other entries. Would you like to PR this?

**Comment by hdm** [comment]
I can include this change in my next rollup PR if you prefer (should be in the next few days).

**Comment by nstylepro** [comment]
I can PR, tried to push my local branch but I do not have appropriate permissions

**Comment by hdm** [comment]
Thanks! Take a look at https://github.com/rapid7/recog/blob/master/CONTRIBUTING.md for instructions. The CPE/normalization stuff is not needed for this small change.

**Comment by nstylepro** [comment]
https://github.com/rapid7/recog/pull/286

**Comment by tsellers-r7** [comment]
The issue has been addressed in PR #286 and #291
