### ISSUE TITLE
Can you provide working example i not sure what content needed

### ISSUE THREAD

**Issue by jamieduk** [rapid7/recog#290]
CRITICAL:root:Expecting exactly 3 arguments; recog XML file, CPE 2.3 XML dictionary, JSON remapping, got 0

its expecting files but dont know what is expected in the file if anything!

**Comment by tsellers-r7** [comment]
What command are you running?

**Comment by tsellers-r7** [comment]
As a note, running `update_cpes.py` is only really useful if you are submitting content.
