### ISSUE TITLE
documentation error - broken link in README.md

### ISSUE THREAD

**Issue by talltechy** [rapid7/recog#294]
**Describe the bug**
Invalid URL in README.md for FLAG_MAP documentation

**To Reproduce**

1. go to README.md
2. go to section: Fingerprints
3. Find the line with: See [the Recog documentation for `FLAG_MAP`](http://www.rubydoc.info/gems/recog/Recog/Fingerprint/RegexpFactory#FLAG_MAP-constant) for more information.
4. Click the link

**Expected behavior**
working URL in documentation

**Comment by gschneider-r7** [comment]
It looks like the docs are not working since version 2.3.13; only the readme gets rendered on the RubyDoc site for 2.3.13 and 2.3.14 (latest).

2.3.12 still works: https://www.rubydoc.info/gems/recog/2.3.12/Recog/Fingerprint/RegexpFactory#FLAG_MAP-constant

**Comment by tsellers-r7** [comment]
Unrelated to this, I just released v2.3.15. The link above wasn't working before but is working now.

**Comment by gschneider-r7** [comment]
Might be a caching issue but the nav menu isn't populating for me still, though the direct link does work now.
