### ISSUE TITLE
regex fail to work on example

### ISSUE THREAD

**Issue by nstylepro** [rapid7/recog#304]
https://github.com/rapid7/recog/blob/fe52bbcc54fdf25c11869c526b75158761de0884/xml/telnet_banners.xml#L427

Decoded example is:
"TiMOS-C-12.0.R12 cpm/hops64 ALCATEL SR 7750 Copyright (c) 2000-2015 Alcatel-Lucent.

Banner Shortened For 

Brevity
Login:
"

and when testing on any regex tester seems there is no match...
is there any processing done to the example before testing?

**Comment by tsellers-r7** [comment]
No processing is being done other than converting from base64.  When using regex testers I often find that I have to account for newline/carriage returns that are in the payload but which didn't copy/paste as expected into the tester window.
