### ISSUE TITLE
Automate Github release process

### ISSUE THREAD

**Issue by limhoff-r7** [rapid7/recog#31]
(This is in response to @jhart-r7's email from 2015-02-17 to the recog users)

Travis-CI has integration with the Github release mechanism.  You can automate it as outlined here http://docs.travis-ci.com/user/deployment/releases/.  If you don't want travis-ci doing the releases, you could also just add an action to the `release` task so that `rake release` both releases to Github and rubygems.

If you mention a rake task more than once, each block is run in the order it is declared

```ruby
task :release do
  # first action for `rake release`
end

task :release do
  # second action for `rake release`
end
```

There may also be separate tasks for each part of `rake release`, such as tagging and building and pushing to rubygems and github, in which case you can make the Github release be dependent on the push to git task and the current release task dependent on it

```ruby
task 'release:github' => 'push-to-git' do
  # do stuff with github API
end

task release: 'release:github'
```

**Comment by jhart-r7** [comment]
Thanks!

Integrating this with `rake release` would be ideal.  The API docs are [here](https://developer.github.com/v3/repos/releases/#create-a-release).
