### ISSUE TITLE
wrong attribute name ?

### ISSUE THREAD

**Issue by tech-ozon-io** [rapid7/recog#329]
Hi,

It seems a wrong attribute is used in the file ftp_banners.xml, at line 363 of tree state 75e3f80

```
<param pos="0" name="service.fvendor" value="PureFTPd"/>
```

It seems that name should be `service.vendor` in place of `service.fvendor` (check the "f" letter)

Thierry

**Comment by tsellers-r7** [comment]
You're correct, thanks for catching that. I'll fix in a PR shortly.

**Comment by tsellers-r7** [comment]
Landed, thanks much

**Comment by tech-ozon-io** [comment]
thanks
