### ISSUE TITLE
Proposal: migrate host.id  to hw.serial_number for storing hardware serial numbers

### ISSUE THREAD

**Issue by tsellers-r7** [rapid7/recog#364]
**Proposal**: Store hardware serial numbers in `hw.serial_number` instead of `host.id`.

In some cases recog is using `host.id` to store hardware serial numbers when they are captured from banners.  I would like to change this, where appropriate, to a _*new field*_ `hw.serial_number`. This would make it more clear as to what is being captured and move the data to a more appropriate context (`hw`).

https://github.com/rapid7/recog/search?q=host.id

In the cases where we have existing vendor specific serial numbers I would duplicate these values in `hw.serial_number` unless stakeholders indicate that these are not being used at all.

https://github.com/rapid7/recog/search?q=serial_number

Any feedback on this change would be greatly appreciated!

CC:  @hdm @dabdine

**Comment by hdm** [comment]
+1 here, thanks!

**Comment by rkirk-r7** [comment]
+1 too

**Comment by tsellers-r7** [comment]
I have opened PR #366  to implement this change.

**Comment by tsellers-r7** [comment]
The change has been landed. Thanks for the feedback here and elsewhere folks.
