### ISSUE TITLE
New anti-DoS patterns break Go regexp support with: invalid repeat count: `{0,1024}`

### ISSUE THREAD

**Issue by hdm** [rapid7/recog#370]
**Describe the bug**

The recent change to use {0,maxLength} prefixes broke Recog use under Go since 1024 is above the maximum limit of 1000.

**To Reproduce**

This Go code reproduces the problem with the new fingerprints:

```
package main

import (
        "regexp"
)

func main() {
        regexp.MustCompile(`^\s{0,1024}APC FTP server ready\.$`)
}
```

```
$ go run main.go
panic: regexp: Compile(`^\s{0,1024}APC FTP server ready\.$`): error parsing regexp: invalid repeat count: `{0,1024}`

goroutine 1 [running]:
regexp.MustCompile(0x781970, 0x22, 0xc0000200b8)
        C:/Program Files/Go/src/regexp/regexp.go:311 +0x15f
main.main()
        C:/Users/Developer/go/recog-go/r/t.go:8 +0x3d
exit status 2
```

To fix the issue, change 0,1024 instances to 0,1000

**Comment by tsellers-r7** [comment]
@hdm - This is fixed now.  Thanks for bringing this up, sorry that it happened in the first place.  We hope to have guardrails in place soonish that will prevent this from happening.

**Comment by hdm** [comment]
thanks!
