### ISSUE TITLE
Add RuboCop (linter) workflow

### ISSUE THREAD

**Issue by mkienow-r7** [rapid7/recog#417]
**Is your feature request related to a problem? Please describe.**
Make it easier for contributors and maintainers to ensure code adheres to a proper style and format.

**Describe the solution you'd like**
Run RuboCop on push to main branch and on pull requests.
* Add `.rubocop.yml` configuration to the root directory for controlling RuboCop’s behaviour
* Add workflow `.github/workflows/rubocop.yml` that runs RuboCop on `push` and `pull_request`

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by adfoster-r7** [comment]
Would we want this issue moved over to the https://github.com/rapid7/recog-ruby repo? Or should rubocop be applied to both repositories

**Comment by mkienow-r7** [comment]
@adfoster-r7 Yes, recog-ruby needs this work. This issue was opened before the repository split. I created a new issue on recog-ruby, and I'm going to leave this open since we have a handful of Ruby scripts on this repository.

**Comment by adfoster-r7** [comment]
Closed by https://github.com/rapid7/recog/pull/579
