### ISSUE TITLE
warning pops up regularly from recog in the context of metasploit framework

### ISSUE THREAD

**Issue by bcook-r7** [rapid7/recog#47]
This warning has begun regularly occurring within metasploit framework's msfconsole:

recog-1.0.27/lib/recog/fingerprint/regexp_factory.rb:33: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression

It seems to appear randomly (not necessarily in response to any particular action being done in framework), so it is not clear what to do to reproduce it yet.

**Comment by bcook-r7** [comment]
Running the specs, I see the same warning. It appears that this pattern from ./xml/mysql_banners.xml causes the warning to popup, though there may be others:

```
<fingerprint pattern="^(\d{1,2}\.\d{1,3}\.\h{1,3})(?:-\d{1,2}\.\d{1,3}\.\h{1,4})?-MariaDB.+~sid-wsrep(?:-log)?$">
```

**Comment by jhart-r7** [comment]
I (unfortunately) admit that I've seen those too and didn't do anything. Any idea which `+` or `?` in particular is the problem?  In the provided example they seem fine.

**Comment by themetric** [comment]
Haven't figured out the one above yet, but found another one that popped up from running the specs: 
`/^(\d{1,2}\.\d{1,3}\.\h{1,3})(?:[^+]+)?\+tld\d/`
and the problem portion seems to be `[^+]+` which appears in many of the mysql patterns.  I think the redundancy is the double `+` which is saying "one or more of, one or more of."  If you remove the second `+` the warning goes away.  Haven't tested yet whether all the matches still work after a change like that.

**Comment by bcook-r7** [comment]
For /^(\d{1,2}\.\d{1,3}\.\h{1,3})(?:[^+]+)?\+tld\d/ removing the second + causes it to fail the first test case. I think I tried something like /^(\d{1,2}\.\d{1,3}\.\h{1,3})(.*)tld\d/ which IIRC seemed to match the version string in both test cases, but caused more results than desired to come back.

**Comment by pdeardorff-r7** [comment]
Thank goodness for `recog_verify`, I hadn't seen that before and was having to catch the warning out of rspec.  I think the culprit ended up being `(?:[^+]+)?` which I replaced with `([^+]+)?` and the warning went away with all the tests still passing.  Even though the MariaDB fingerprint above wasn't causing a warning for me, I changed it as well.  I noticed `(?:whatever)?` is used frequently, and I think it's ok, but when the two + signs were inside of the group then it was considered redundant.  I tested on ruby versions 1.9.3, 2.0.0, 2.1.5, and 2.2.0 and couldn't get any more warnings to come up.

**Comment by bcook-r7** [comment]
Nice, thanks!

**Comment by bcook-r7** [comment]
Would you mind submitting a PR @pdeardorff-r7 ?

**Comment by pdeardorff-r7** [comment]
Sure thing I'll work on it now.
